### ISSUE TITLE
Zpětná vazba životopis

### ISSUE THREAD

**Issue by IxAriela** [nasajana/2022-ukol-01-zivotopis#1]
Ahoj,

omlouvám se, že mi to tak trvalo. Když jsem viděla tvoji stránku poprvé, velmi mě překvapilo, jak pěkně vypadá a jak je propracovaná :) sorry, ne u Fb mě zase pobavilo :) Taky chválím za nezalomitelné mezery. A ono je to dokonce responsivní, super!

Fonty, obzvlášt google fonty, jdou vložit i čistě html tagem, takže není potřeba tam dávat css input :)

Co je base="" u odkazu? Přiznám se, že to vůbec neznám, ale hlavně to není ani u definice na W3Schools, což je oficiální zdroj u HTML.

Většinou se omezená šířka dává až na .container, ne na body, to se nechává na celou šířku. Takhle tam sice tu třídu v html máš, ale vlastně úplně zbytečně, když na ní není žádné css.

Popravdě mám z toho celkově pocit, že HTML a CSS umíš snad líp než já (rozhodně používáš některé modernější postupy, ke kterým se já nezvládám dokopat) :-D

Rozhodně tam nemáš žádnou chybu, která by byla třeba opravit, takže až si toto přečteš, tak to klidně uzavři :)

**Comment by nasajana** [comment]
Ahoj, děkuji za milé hodnocení. HTML a CSS možná teoreticky trochu umím, stále je co se učit, dokonce myslím, že čím dál, tím víc vidím co neumím a opakovat potřebuji stále, i tento kurz je moje osobní dokopávání :)
Ani nevím, z jakého důvodu jsem u ikonek ponechala base, info je zde: https://www.w3schools.com/tags/tag_base.asp.
Děkuji za radu s body a container, budu na to pamatovat.
